import os
import shutil
from rdkit import Chem

def get_unique_path(path):
    """
    Returns a unique path (file or directory). If path exists, returns path_1, path_2, etc.
    """
    if not os.path.exists(path):
        return path
        
    base, ext = os.path.splitext(path)
    n = 1
    while True:
        new_path = f"{base}_{n}{ext}"
        if not os.path.exists(new_path):
            return new_path
        n += 1

def rdkit_to_xyz(mol):
    """
    Convert RDKit molecule to XYZ string format for PySCF.
    """
    if not mol:
        return ""
    
    # Ensure standard handling
    # PySCF expects:
    # Symbol x y z
    conf = mol.GetConformer()
    lines = []
    num_atoms = mol.GetNumAtoms()
    lines.append(str(num_atoms))
    lines.append("Generated by PySCF Plugin")
    
    for i in range(num_atoms):
        pos = conf.GetAtomPosition(i)
        sym = mol.GetAtomWithIdx(i).GetSymbol()
        lines.append(f"{sym} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    
    return "\n".join(lines)

def update_molecule_from_xyz(context, xyz_content, mark_modified=True):
    """
    Update the current molecule in context with new coordinates from XYZ content.
    mark_modified: If True (default), allows the main window to mark the project as 'dirty' (*). 
                   If False, suppresses the dirty flag (useful for transient viewing).
    """
    # This is tricky because recreating the molecule destroys properties.
    # We should try to align conformers if possible, or just load fresh.
    # Simple approach: Load new mol from XYZ block
    
    # Depending on format (PDB or XYZ), we might need parsing.
    # PySCF might return PDB format from 'to_pdb()'.
    
    # If xyz_content looks like PDB:
    new_mol = None
    if "ATOM" in xyz_content:
        new_mol = Chem.MolFromPDBBlock(xyz_content)
    else:
        # Assume XYZ block (skip first 2 lines if standard XYZ file, or raw atoms if just lines)
        # Check if first line is number
        lines = xyz_content.strip().split('\n')
        if len(lines) > 2 and lines[0].strip().isdigit():
             # Standard XYZ
             new_mol = Chem.MolFromXYZBlock(xyz_content)
        else:
             # Just atom lines? Not standard XYZ.
             # Construct standard XYZ
             count = len(lines)
             raw_xyz = f"{count}\nGenerated by PySCF\n{xyz_content}"
             new_mol = Chem.MolFromXYZBlock(raw_xyz)
             
    if new_mol:
        # User requested: determine bond and bond order by rdkit
        try:
            from rdkit.Chem import rdDetermineBonds
            rdDetermineBonds.DetermineConnectivity(new_mol)
            rdDetermineBonds.DetermineBondOrders(new_mol, charge=0) # Assuming neutral or use context?
        except ImportError:
            # Fallback for older RDKit?
            pass
        except Exception as e:
            print(f"Warning: Could not determine bonds: {e}")

        # Preserve Dirty State if requested NOT to mark modified
        mw = context.get_main_window()
        was_dirty = False
        should_suppress = not mark_modified
        
        if should_suppress:
            try:
                if mw and hasattr(mw, 'has_unsaved_changes'):
                    was_dirty = mw.has_unsaved_changes
            except: pass

        context.current_molecule = new_mol
        
        # Restore Dirty State
        if should_suppress:
            try:
                if mw and hasattr(mw, 'has_unsaved_changes'):
                    mw.has_unsaved_changes = was_dirty
                    mw.update_window_title()
            except: pass
